"""
VAULT 13: Screen Functions
Major UI screens like launcher, tutorial, etc.
"""

import time

from colors import C
from platform_utils import clear_screen


def show_launcher() -> str:
    """Beautiful game launcher screen"""
    clear_screen()

    print(f"{C.HEADER}{C.BOLD}")
    print("╔═══════════════════════════════════════════════════════════════════════╗")
    print("║                                                                       ║")
    print("║   ██╗   ██╗ █████╗ ██╗   ██╗██╗  ████████╗    ██╗██████╗            ║")
    print("║   ██║   ██║██╔══██╗██║   ██║██║  ╚══██╔══╝    ╚═╝╚════██╗           ║")
    print("║   ██║   ██║███████║██║   ██║██║     ██║        ██║ █████╔╝           ║")
    print("║   ╚██╗ ██╔╝██╔══██║██║   ██║██║     ██║        ██║ ╚═══██╗           ║")
    print("║    ╚████╔╝ ██║  ██║╚██████╔╝███████╗██║        ██║██████╔╝           ║")
    print("║     ╚═══╝  ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝        ╚═╝╚═════╝            ║")
    print("║                                                                       ║")
    print("║              🌟 v9.0: THE ULTIMATE EVOLUTION 🌟                       ║")
    print("║                                                                       ║")
    print("║       Modular Architecture Edition - Clean, Fast, Extensible!         ║")
    print("║                                                                       ║")
    print("╚═══════════════════════════════════════════════════════════════════════╝")
    print(f"{C.RESET}\n")

    print(f"{C.SUCCESS}{C.BOLD}Main Menu:{C.RESET}")
    print(f"  {C.SUCCESS}[1]{C.RESET} 🎮 New Game")
    print(f"  {C.SUCCESS}[2]{C.RESET} 💾 Load Game")
    print(f"  {C.SUCCESS}[3]{C.RESET} 🎓 Tutorial")
    print(f"  {C.SUCCESS}[4]{C.RESET} 🎬 Demo Mode")
    print(f"  {C.SUCCESS}[5]{C.RESET} 🏆 Leaderboard")
    print(f"  {C.SUCCESS}[6]{C.RESET} ⚙️  Settings")
    print(f"  {C.SUCCESS}[7]{C.RESET} 📖 Credits")
    print(f"  {C.DANGER}[0]{C.RESET} 🚪 Exit\n")

    return input(f"{C.BOLD}Select option: {C.RESET}").strip()


def show_tutorial():
    """Interactive tutorial for new players"""
    clear_screen()

    print(f"{C.INFO}{C.BOLD}╔═══════════════════════════════════════════════════════════════╗{C.RESET}")
    print(f"{C.INFO}{C.BOLD}║              🎓 VAULT 13 INTERACTIVE TUTORIAL                 ║{C.RESET}")
    print(f"{C.INFO}{C.BOLD}╚═══════════════════════════════════════════════════════════════╝{C.RESET}\n")

    tutorials = [
        ("Welcome to VAULT 13!",
         "You are the Overseer of Vault 13, responsible for the survival\n" +
         "of all dwellers. Your job is to manage resources, build rooms,\n" +
         "and keep everyone alive!"),

        ("Resources",
         "You need 3 basic resources:\n" +
         "  ⚡ POWER - Generated by Power Generators\n" +
         "  💧 WATER - Produced by Water Treatment plants\n" +
         "  🍖 FOOD - Made in Diners\n\n" +
         "Each dweller consumes 1 of each per turn!"),

        ("Building Rooms",
         "Press [B] to build new rooms.\n" +
         "  1. Select a floor\n" +
         "  2. Pick an empty position\n" +
         "  3. Choose the room type\n" +
         "  4. Wait 2 turns for construction"),

        ("Managing Dwellers",
         "Press [D] to manage your dwellers.\n" +
         "  • Assign them to rooms for production\n" +
         "  • Monitor health ❤️ and happiness 😊\n" +
         "  • Level them up through work\n" +
         "  • Send them on expeditions [X]"),

        ("Advanced Features",
         "Once comfortable, explore:\n" +
         "  [T] Tech Tree - Research upgrades\n" +
         "  [F] Families - Breed new dwellers\n" +
         "  [V] Vault Expansion - Build up to 15 floors!\n" +
         "  [1] Dashboard - See everything at a glance"),

        ("Getting Help",
         "Press [?] anytime for full controls.\n" +
         "Press [1] for Dashboard with warnings.\n" +
         "Press [~] for Quick Actions.\n\n" +
         "Good luck, Overseer! 🏛️")
    ]

    for i, (title, content) in enumerate(tutorials, 1):
        print(f"{C.BOLD}Step {i}/{len(tutorials)}: {title}{C.RESET}\n")
        print(content)
        print(f"\n{C.DIM}Press Enter to continue...{C.RESET}")
        input()
        clear_screen()
        print(f"{C.INFO}{C.BOLD}╔═══════════════════════════════════════════════════════════════╗{C.RESET}")
        print(f"{C.INFO}{C.BOLD}║              🎓 VAULT 13 INTERACTIVE TUTORIAL                 ║{C.RESET}")
        print(f"{C.INFO}{C.BOLD}╚═══════════════════════════════════════════════════════════════╝{C.RESET}\n")

    print(f"{C.SUCCESS}✓ Tutorial complete! Ready to play!{C.RESET}\n")
    input(f"{C.DIM}Press Enter to start...{C.RESET}")


def show_achievement_animation(achievement_name: str):
    """Show ASCII fireworks animation for achievement"""
    clear_screen()

    frames = [
        ["                    *                    ",
         "                                         ",
         "                                         ",
         "                                         "],

        ["               *         *               ",
         "                    *                    ",
         "                                         ",
         "                                         "],

        ["          *                   *          ",
         "              *         *                ",
         "                    *                    ",
         "                                         "],

        ["     *                             *     ",
         "         *                   *           ",
         "              *         *                ",
         "                    *                    "]
    ]

    for frame in frames:
        clear_screen()
        print(f"{C.QUEST}{C.BOLD}")
        print("╔═══════════════════════════════════════════════════════════════╗")
        for line in frame:
            print(f"║ {line} ║")
        print("║                                                               ║")
        print("║           🏆 ACHIEVEMENT UNLOCKED! 🏆                         ║")
        print("║                                                               ║")
        print(f"║                {achievement_name:^40}               ║")
        print("║                                                               ║")
        print("╚═══════════════════════════════════════════════════════════════╝")
        print(f"{C.RESET}")
        time.sleep(0.3)

    time.sleep(1)


def show_performance_dashboard(game):
    """Show performance and optimization stats"""
    clear_screen()

    print(f"{C.TECH}{C.BOLD}╔═══════════════════════════════════════════════════════════════╗{C.RESET}")
    print(f"{C.TECH}{C.BOLD}║              📊 PERFORMANCE DASHBOARD                        ║{C.RESET}")
    print(f"{C.TECH}{C.BOLD}╚═══════════════════════════════════════════════════════════════╝{C.RESET}\n")

    print(f"{C.BOLD}GAME STATS:{C.RESET}")
    print(f"  Architecture: {C.SUCCESS}Modular Package{C.RESET}")
    print(f"  Features: {C.SUCCESS}65+ implemented{C.RESET}")
    print(f"  Day: {game.day}")
    print(f"  Dwellers: {len(game.dwellers)}")

    room_count = sum(1 for floor in game.vault_layout
                    for room in floor if room.room_type.value != "Empty")
    print(f"  Rooms: {room_count}")

    print(f"\n{C.BOLD}MEMORY USAGE:{C.RESET}")
    print(f"  Events Logged: {len(game.event_log)}")
    print(f"  Major Events: {len(game.major_events)}")
    print(f"  Notifications: {len(game.notifications)}")
    print(f"  Resource History: {len(game.resource_history.get('power', []))} data points")

    print(f"\n{C.BOLD}ARCHITECTURE:{C.RESET}")
    print(f"  {C.SUCCESS}✓{C.RESET} Modular package structure")
    print(f"  {C.SUCCESS}✓{C.RESET} Separated concerns (models, ui, systems)")
    print(f"  {C.SUCCESS}✓{C.RESET} Clean imports and dependencies")
    print(f"  {C.SUCCESS}✓{C.RESET} Extensible design")

    input(f"\n{C.DIM}Press Enter...{C.RESET}")


def show_intro():
    """Show game introduction"""
    clear_screen()

    intro = f"""
{C.HEADER}{C.BOLD}
╔═══════════════════════════════════════════════════════════════════════════╗
║                                                                           ║
║    🌟 VAULT 13: SURVIVAL PROTOCOL v9.0 - THE ULTIMATE EVOLUTION 🌟       ║
║                                                                           ║
║                      Modular Architecture Edition                         ║
║                                                                           ║
╠═══════════════════════════════════════════════════════════════════════════╣
║                                                                           ║
║  The year is 2077. The bombs have fallen.                                 ║
║                                                                           ║
║  You are the newly appointed Overseer of Vault 13, one of the few        ║
║  remaining sanctuaries for humanity. Your mission: ensure the survival   ║
║  of your vault dwellers in this harsh post-apocalyptic world.            ║
║                                                                           ║
║  Manage resources. Build rooms. Train dwellers. Explore the wasteland.   ║
║  Make difficult choices. The fate of humanity rests in your hands.       ║
║                                                                           ║
╚═══════════════════════════════════════════════════════════════════════════╝
{C.RESET}

{C.WARNING}Your dwellers now have mental health and can get sick!{C.RESET}
{C.INFO}Manage stress, prevent epidemics, and keep everyone alive!{C.RESET}
"""
    print(intro)
    input(f"\n{C.BOLD}Press Enter to begin...{C.RESET}")
